import { SchoolIntrfc } from "./modules";
export const schoolSheduleData: SchoolIntrfc[] = [
  {
    "date": "2026-03-17",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Music",
    "sub_2": "Geography",
    "sub_3": "Physics",
    "sub_4": "Art",
    "sub_5": "Mathematics",
    "sub_6": "Literature",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Art",
    "sub_2": "Nature",
    "sub_3": "Chemistry",
    "sub_4": "Literature",
    "sub_5": "Physics",
    "sub_6": "Mathematics",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Art",
    "sub_2": "Literature",
    "sub_3": "Music",
    "sub_4": "Chemistry",
    "sub_5": "Chemistry",
    "sub_6": "Nature",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Biology",
    "sub_2": "Chemistry",
    "sub_3": "Biology",
    "sub_4": "Chemistry",
    "sub_5": "English",
    "sub_6": "Biology",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Mathematics",
    "sub_2": "Biology",
    "sub_3": "English",
    "sub_4": "Mathematics",
    "sub_5": "Chemistry",
    "sub_6": "PE",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Geography",
    "sub_3": "Chemistry",
    "sub_4": "Nature",
    "sub_5": "Nature",
    "sub_6": "Nature",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Mathematics",
    "sub_2": "Music",
    "sub_3": "Literature",
    "sub_4": "Chemistry",
    "sub_5": "Mathematics",
    "sub_6": "Chemistry",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "Mathematics",
    "sub_3": "Literature",
    "sub_4": "Mathematics",
    "sub_5": "Music",
    "sub_6": "PE",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-17",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "English",
    "sub_2": "English",
    "sub_3": "Physics",
    "sub_4": "Chemistry",
    "sub_5": "PE",
    "sub_6": "Nature",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Geography",
    "sub_2": "Literature",
    "sub_3": "Geography",
    "sub_4": "Geography",
    "sub_5": "Mathematics",
    "sub_6": "Nature",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Biology",
    "sub_2": "Chemistry",
    "sub_3": "Biology",
    "sub_4": "English",
    "sub_5": "Music",
    "sub_6": "Literature",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Chemistry",
    "sub_2": "Chemistry",
    "sub_3": "Art",
    "sub_4": "Mathematics",
    "sub_5": "Physics",
    "sub_6": "Nature",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "Literature",
    "sub_3": "History",
    "sub_4": "Chemistry",
    "sub_5": "Literature",
    "sub_6": "History",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "Art",
    "sub_3": "PE",
    "sub_4": "Geography",
    "sub_5": "Chemistry",
    "sub_6": "Literature",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "Nature",
    "sub_3": "Chemistry",
    "sub_4": "English",
    "sub_5": "Biology",
    "sub_6": "Mathematics",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Art",
    "sub_2": "English",
    "sub_3": "History",
    "sub_4": "Physics",
    "sub_5": "English",
    "sub_6": "Mathematics",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Biology",
    "sub_2": "English",
    "sub_3": "Geography",
    "sub_4": "Literature",
    "sub_5": "Literature",
    "sub_6": "Physics",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-18",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "Nature",
    "sub_3": "Physics",
    "sub_4": "Music",
    "sub_5": "Music",
    "sub_6": "Mathematics",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Biology",
    "sub_2": "History",
    "sub_3": "Mathematics",
    "sub_4": "English",
    "sub_5": "Chemistry",
    "sub_6": "English",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Geography",
    "sub_2": "Literature",
    "sub_3": "Art",
    "sub_4": "Geography",
    "sub_5": "Nature",
    "sub_6": "Geography",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "PE",
    "sub_3": "Mathematics",
    "sub_4": "Physics",
    "sub_5": "Chemistry",
    "sub_6": "Geography",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "Art",
    "sub_3": "PE",
    "sub_4": "PE",
    "sub_5": "Art",
    "sub_6": "Nature",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Physics",
    "sub_3": "Geography",
    "sub_4": "Nature",
    "sub_5": "Mathematics",
    "sub_6": "Art",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Biology",
    "sub_2": "Mathematics",
    "sub_3": "Music",
    "sub_4": "Biology",
    "sub_5": "Biology",
    "sub_6": "Art",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Literature",
    "sub_2": "Nature",
    "sub_3": "Mathematics",
    "sub_4": "Literature",
    "sub_5": "Geography",
    "sub_6": "Biology",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "PE",
    "sub_2": "History",
    "sub_3": "Mathematics",
    "sub_4": "Nature",
    "sub_5": "Art",
    "sub_6": "Nature",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-19",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Chemistry",
    "sub_2": "Music",
    "sub_3": "Geography",
    "sub_4": "Literature",
    "sub_5": "Art",
    "sub_6": "PE",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Music",
    "sub_2": "Literature",
    "sub_3": "PE",
    "sub_4": "English",
    "sub_5": "Literature",
    "sub_6": "Chemistry",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "PE",
    "sub_2": "Mathematics",
    "sub_3": "English",
    "sub_4": "PE",
    "sub_5": "Mathematics",
    "sub_6": "English",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Biology",
    "sub_2": "History",
    "sub_3": "PE",
    "sub_4": "Physics",
    "sub_5": "Chemistry",
    "sub_6": "English",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "Music",
    "sub_3": "Art",
    "sub_4": "Geography",
    "sub_5": "PE",
    "sub_6": "Physics",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Nature",
    "sub_2": "History",
    "sub_3": "Physics",
    "sub_4": "Art",
    "sub_5": "English",
    "sub_6": "Mathematics",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "English",
    "sub_2": "Art",
    "sub_3": "Biology",
    "sub_4": "Mathematics",
    "sub_5": "Music",
    "sub_6": "Art",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Mathematics",
    "sub_2": "Nature",
    "sub_3": "History",
    "sub_4": "Chemistry",
    "sub_5": "Art",
    "sub_6": "Nature",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Geography",
    "sub_2": "Mathematics",
    "sub_3": "Geography",
    "sub_4": "Art",
    "sub_5": "Literature",
    "sub_6": "Geography",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-20",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Chemistry",
    "sub_2": "History",
    "sub_3": "Biology",
    "sub_4": "Literature",
    "sub_5": "History",
    "sub_6": "English",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Geography",
    "sub_2": "Mathematics",
    "sub_3": "PE",
    "sub_4": "Physics",
    "sub_5": "Art",
    "sub_6": "Mathematics",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "Art",
    "sub_3": "Art",
    "sub_4": "Chemistry",
    "sub_5": "English",
    "sub_6": "Mathematics",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "PE",
    "sub_2": "PE",
    "sub_3": "Mathematics",
    "sub_4": "Chemistry",
    "sub_5": "Literature",
    "sub_6": "Nature",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Literature",
    "sub_2": "Nature",
    "sub_3": "Biology",
    "sub_4": "Literature",
    "sub_5": "Physics",
    "sub_6": "Geography",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "PE",
    "sub_2": "Geography",
    "sub_3": "Music",
    "sub_4": "PE",
    "sub_5": "Physics",
    "sub_6": "Biology",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Literature",
    "sub_2": "PE",
    "sub_3": "Nature",
    "sub_4": "Geography",
    "sub_5": "Biology",
    "sub_6": "Geography",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "PE",
    "sub_2": "Literature",
    "sub_3": "Literature",
    "sub_4": "Art",
    "sub_5": "History",
    "sub_6": "Physics",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Music",
    "sub_2": "PE",
    "sub_3": "English",
    "sub_4": "Physics",
    "sub_5": "Nature",
    "sub_6": "PE",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-23",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Literature",
    "sub_2": "Mathematics",
    "sub_3": "Music",
    "sub_4": "PE",
    "sub_5": "Literature",
    "sub_6": "Biology",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "Biology",
    "sub_3": "Music",
    "sub_4": "Mathematics",
    "sub_5": "English",
    "sub_6": "Nature",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "Biology",
    "sub_3": "Literature",
    "sub_4": "PE",
    "sub_5": "History",
    "sub_6": "History",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Geography",
    "sub_2": "Literature",
    "sub_3": "Art",
    "sub_4": "Geography",
    "sub_5": "Geography",
    "sub_6": "Physics",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "PE",
    "sub_3": "Chemistry",
    "sub_4": "Mathematics",
    "sub_5": "Music",
    "sub_6": "Geography",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Physics",
    "sub_2": "Literature",
    "sub_3": "Physics",
    "sub_4": "Nature",
    "sub_5": "Literature",
    "sub_6": "Mathematics",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Music",
    "sub_3": "Biology",
    "sub_4": "PE",
    "sub_5": "English",
    "sub_6": "PE",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Biology",
    "sub_2": "Nature",
    "sub_3": "English",
    "sub_4": "English",
    "sub_5": "English",
    "sub_6": "History",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Nature",
    "sub_2": "PE",
    "sub_3": "Mathematics",
    "sub_4": "PE",
    "sub_5": "Biology",
    "sub_6": "Geography",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-24",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "Art",
    "sub_3": "Art",
    "sub_4": "Nature",
    "sub_5": "History",
    "sub_6": "PE",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "PE",
    "sub_2": "Biology",
    "sub_3": "History",
    "sub_4": "Literature",
    "sub_5": "History",
    "sub_6": "Literature",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "History",
    "sub_3": "History",
    "sub_4": "History",
    "sub_5": "Mathematics",
    "sub_6": "Geography",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Biology",
    "sub_2": "Physics",
    "sub_3": "Nature",
    "sub_4": "PE",
    "sub_5": "Geography",
    "sub_6": "Biology",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "Chemistry",
    "sub_3": "Literature",
    "sub_4": "Music",
    "sub_5": "History",
    "sub_6": "Music",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "Physics",
    "sub_3": "Nature",
    "sub_4": "History",
    "sub_5": "Chemistry",
    "sub_6": "History",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Literature",
    "sub_2": "Music",
    "sub_3": "Mathematics",
    "sub_4": "Art",
    "sub_5": "Chemistry",
    "sub_6": "Geography",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Geography",
    "sub_2": "Art",
    "sub_3": "PE",
    "sub_4": "Music",
    "sub_5": "Chemistry",
    "sub_6": "Art",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "Nature",
    "sub_3": "PE",
    "sub_4": "History",
    "sub_5": "Physics",
    "sub_6": "Mathematics",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-25",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Nature",
    "sub_2": "English",
    "sub_3": "Biology",
    "sub_4": "History",
    "sub_5": "Chemistry",
    "sub_6": "Biology",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Music",
    "sub_2": "Mathematics",
    "sub_3": "English",
    "sub_4": "Chemistry",
    "sub_5": "English",
    "sub_6": "History",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Biology",
    "sub_2": "Art",
    "sub_3": "Nature",
    "sub_4": "Geography",
    "sub_5": "Chemistry",
    "sub_6": "English",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "Biology",
    "sub_3": "Art",
    "sub_4": "Biology",
    "sub_5": "History",
    "sub_6": "Chemistry",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Literature",
    "sub_3": "Art",
    "sub_4": "English",
    "sub_5": "Biology",
    "sub_6": "Biology",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Geography",
    "sub_3": "Nature",
    "sub_4": "PE",
    "sub_5": "Mathematics",
    "sub_6": "Music",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Art",
    "sub_2": "Nature",
    "sub_3": "English",
    "sub_4": "Geography",
    "sub_5": "Art",
    "sub_6": "Nature",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Nature",
    "sub_2": "Biology",
    "sub_3": "Art",
    "sub_4": "Physics",
    "sub_5": "Literature",
    "sub_6": "Nature",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Geography",
    "sub_2": "Art",
    "sub_3": "Music",
    "sub_4": "Chemistry",
    "sub_5": "Literature",
    "sub_6": "PE",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-03-26",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Nature",
    "sub_2": "Physics",
    "sub_3": "Chemistry",
    "sub_4": "Literature",
    "sub_5": "Nature",
    "sub_6": "Mathematics",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Music",
    "sub_2": "Art",
    "sub_3": "Physics",
    "sub_4": "Chemistry",
    "sub_5": "Mathematics",
    "sub_6": "Physics",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "Biology",
    "sub_3": "Geography",
    "sub_4": "Mathematics",
    "sub_5": "Art",
    "sub_6": "Music",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Literature",
    "sub_2": "Physics",
    "sub_3": "History",
    "sub_4": "Physics",
    "sub_5": "Biology",
    "sub_6": "Geography",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Mathematics",
    "sub_2": "Chemistry",
    "sub_3": "Physics",
    "sub_4": "Nature",
    "sub_5": "Geography",
    "sub_6": "Geography",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "PE",
    "sub_2": "Biology",
    "sub_3": "Physics",
    "sub_4": "Mathematics",
    "sub_5": "Physics",
    "sub_6": "Physics",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Biology",
    "sub_2": "Biology",
    "sub_3": "Art",
    "sub_4": "Literature",
    "sub_5": "Art",
    "sub_6": "Literature",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "English",
    "sub_2": "Chemistry",
    "sub_3": "Music",
    "sub_4": "Nature",
    "sub_5": "Nature",
    "sub_6": "Biology",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Geography",
    "sub_2": "History",
    "sub_3": "Literature",
    "sub_4": "Geography",
    "sub_5": "Geography",
    "sub_6": "Chemistry",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-27",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "PE",
    "sub_3": "History",
    "sub_4": "Music",
    "sub_5": "Biology",
    "sub_6": "PE",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Art",
    "sub_2": "Physics",
    "sub_3": "History",
    "sub_4": "History",
    "sub_5": "PE",
    "sub_6": "Music",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "Chemistry",
    "sub_3": "Biology",
    "sub_4": "Physics",
    "sub_5": "Nature",
    "sub_6": "Literature",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Literature",
    "sub_2": "Literature",
    "sub_3": "PE",
    "sub_4": "Biology",
    "sub_5": "Art",
    "sub_6": "English",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "PE",
    "sub_2": "History",
    "sub_3": "Physics",
    "sub_4": "Physics",
    "sub_5": "Mathematics",
    "sub_6": "Physics",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "PE",
    "sub_2": "History",
    "sub_3": "History",
    "sub_4": "PE",
    "sub_5": "Nature",
    "sub_6": "Art",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Art",
    "sub_2": "Geography",
    "sub_3": "Chemistry",
    "sub_4": "Chemistry",
    "sub_5": "PE",
    "sub_6": "Music",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Mathematics",
    "sub_2": "Chemistry",
    "sub_3": "Geography",
    "sub_4": "Music",
    "sub_5": "Geography",
    "sub_6": "English",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Art",
    "sub_2": "Art",
    "sub_3": "English",
    "sub_4": "Nature",
    "sub_5": "Biology",
    "sub_6": "PE",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-29",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Music",
    "sub_2": "Music",
    "sub_3": "Art",
    "sub_4": "Nature",
    "sub_5": "Geography",
    "sub_6": "Geography",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "Biology",
    "sub_3": "Geography",
    "sub_4": "Art",
    "sub_5": "Physics",
    "sub_6": "Chemistry",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "Art",
    "sub_3": "English",
    "sub_4": "Art",
    "sub_5": "PE",
    "sub_6": "Physics",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Geography",
    "sub_2": "English",
    "sub_3": "Mathematics",
    "sub_4": "Music",
    "sub_5": "Geography",
    "sub_6": "English",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "Literature",
    "sub_3": "Literature",
    "sub_4": "Nature",
    "sub_5": "Literature",
    "sub_6": "English",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Biology",
    "sub_2": "Music",
    "sub_3": "Biology",
    "sub_4": "Biology",
    "sub_5": "English",
    "sub_6": "PE",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Biology",
    "sub_2": "Biology",
    "sub_3": "Physics",
    "sub_4": "Biology",
    "sub_5": "Geography",
    "sub_6": "Chemistry",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Mathematics",
    "sub_2": "History",
    "sub_3": "Art",
    "sub_4": "Chemistry",
    "sub_5": "Music",
    "sub_6": "Mathematics",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "Physics",
    "sub_3": "Mathematics",
    "sub_4": "Nature",
    "sub_5": "Biology",
    "sub_6": "History",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-30",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Mathematics",
    "sub_2": "Physics",
    "sub_3": "Biology",
    "sub_4": "Literature",
    "sub_5": "Art",
    "sub_6": "Nature",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Art",
    "sub_2": "Geography",
    "sub_3": "Literature",
    "sub_4": "English",
    "sub_5": "Art",
    "sub_6": "Literature",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "Physics",
    "sub_3": "Geography",
    "sub_4": "Geography",
    "sub_5": "Mathematics",
    "sub_6": "Geography",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Nature",
    "sub_2": "Mathematics",
    "sub_3": "Music",
    "sub_4": "English",
    "sub_5": "Nature",
    "sub_6": "Nature",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Geography",
    "sub_2": "Art",
    "sub_3": "Nature",
    "sub_4": "Biology",
    "sub_5": "Literature",
    "sub_6": "History",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Geography",
    "sub_2": "Literature",
    "sub_3": "Geography",
    "sub_4": "English",
    "sub_5": "Literature",
    "sub_6": "Biology",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "English",
    "sub_2": "PE",
    "sub_3": "English",
    "sub_4": "Music",
    "sub_5": "Geography",
    "sub_6": "Music",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "PE",
    "sub_2": "Music",
    "sub_3": "PE",
    "sub_4": "Geography",
    "sub_5": "PE",
    "sub_6": "Nature",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Music",
    "sub_2": "Biology",
    "sub_3": "PE",
    "sub_4": "Music",
    "sub_5": "Geography",
    "sub_6": "PE",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-03-31",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Nature",
    "sub_2": "Nature",
    "sub_3": "Music",
    "sub_4": "Physics",
    "sub_5": "Mathematics",
    "sub_6": "Geography",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "Mathematics",
    "sub_3": "Art",
    "sub_4": "Art",
    "sub_5": "Art",
    "sub_6": "Biology",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Music",
    "sub_2": "Mathematics",
    "sub_3": "PE",
    "sub_4": "Art",
    "sub_5": "Mathematics",
    "sub_6": "Art",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "History",
    "sub_3": "Nature",
    "sub_4": "Music",
    "sub_5": "Music",
    "sub_6": "Nature",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Biology",
    "sub_2": "History",
    "sub_3": "Nature",
    "sub_4": "PE",
    "sub_5": "Music",
    "sub_6": "Physics",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Physics",
    "sub_2": "Nature",
    "sub_3": "English",
    "sub_4": "Art",
    "sub_5": "Chemistry",
    "sub_6": "Music",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Physics",
    "sub_2": "Nature",
    "sub_3": "PE",
    "sub_4": "History",
    "sub_5": "History",
    "sub_6": "Geography",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "Literature",
    "sub_3": "Mathematics",
    "sub_4": "Nature",
    "sub_5": "Literature",
    "sub_6": "Nature",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Art",
    "sub_2": "History",
    "sub_3": "Music",
    "sub_4": "Chemistry",
    "sub_5": "Nature",
    "sub_6": "Literature",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-04-01",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Literature",
    "sub_2": "Chemistry",
    "sub_3": "Chemistry",
    "sub_4": "Mathematics",
    "sub_5": "Chemistry",
    "sub_6": "Chemistry",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Chemistry",
    "sub_2": "English",
    "sub_3": "Geography",
    "sub_4": "Chemistry",
    "sub_5": "Nature",
    "sub_6": "PE",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Music",
    "sub_2": "History",
    "sub_3": "Chemistry",
    "sub_4": "Biology",
    "sub_5": "Art",
    "sub_6": "Biology",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "PE",
    "sub_2": "Physics",
    "sub_3": "History",
    "sub_4": "Geography",
    "sub_5": "English",
    "sub_6": "Physics",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Literature",
    "sub_2": "Geography",
    "sub_3": "Nature",
    "sub_4": "Biology",
    "sub_5": "History",
    "sub_6": "History",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "English",
    "sub_2": "Mathematics",
    "sub_3": "Art",
    "sub_4": "Music",
    "sub_5": "Mathematics",
    "sub_6": "Geography",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "History",
    "sub_3": "Chemistry",
    "sub_4": "Mathematics",
    "sub_5": "Chemistry",
    "sub_6": "Mathematics",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "English",
    "sub_2": "Literature",
    "sub_3": "Literature",
    "sub_4": "Mathematics",
    "sub_5": "Physics",
    "sub_6": "Nature",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "History",
    "sub_3": "Mathematics",
    "sub_4": "Chemistry",
    "sub_5": "English",
    "sub_6": "Literature",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-02",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Art",
    "sub_2": "Music",
    "sub_3": "Mathematics",
    "sub_4": "Art",
    "sub_5": "English",
    "sub_6": "Biology",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "Mathematics",
    "sub_3": "Biology",
    "sub_4": "Physics",
    "sub_5": "Geography",
    "sub_6": "PE",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Nature",
    "sub_2": "English",
    "sub_3": "Physics",
    "sub_4": "Nature",
    "sub_5": "English",
    "sub_6": "Biology",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Biology",
    "sub_2": "English",
    "sub_3": "PE",
    "sub_4": "Biology",
    "sub_5": "Music",
    "sub_6": "Chemistry",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Biology",
    "sub_2": "Music",
    "sub_3": "History",
    "sub_4": "PE",
    "sub_5": "Literature",
    "sub_6": "Literature",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Nature",
    "sub_3": "Geography",
    "sub_4": "Mathematics",
    "sub_5": "Geography",
    "sub_6": "PE",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "PE",
    "sub_3": "English",
    "sub_4": "Art",
    "sub_5": "History",
    "sub_6": "Nature",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Literature",
    "sub_2": "Music",
    "sub_3": "Literature",
    "sub_4": "Geography",
    "sub_5": "Nature",
    "sub_6": "PE",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "Biology",
    "sub_3": "Geography",
    "sub_4": "Nature",
    "sub_5": "Physics",
    "sub_6": "PE",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-05",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "English",
    "sub_2": "Art",
    "sub_3": "Nature",
    "sub_4": "English",
    "sub_5": "Literature",
    "sub_6": "Geography",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Chemistry",
    "sub_2": "Biology",
    "sub_3": "PE",
    "sub_4": "PE",
    "sub_5": "Biology",
    "sub_6": "Geography",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "Literature",
    "sub_3": "Biology",
    "sub_4": "Art",
    "sub_5": "Art",
    "sub_6": "Biology",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Literature",
    "sub_2": "Biology",
    "sub_3": "Nature",
    "sub_4": "History",
    "sub_5": "Biology",
    "sub_6": "Art",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Geography",
    "sub_2": "Geography",
    "sub_3": "History",
    "sub_4": "English",
    "sub_5": "Biology",
    "sub_6": "Chemistry",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Nature",
    "sub_3": "Geography",
    "sub_4": "Chemistry",
    "sub_5": "Geography",
    "sub_6": "History",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "PE",
    "sub_2": "Nature",
    "sub_3": "History",
    "sub_4": "Physics",
    "sub_5": "Art",
    "sub_6": "Art",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Physics",
    "sub_2": "Nature",
    "sub_3": "English",
    "sub_4": "Nature",
    "sub_5": "English",
    "sub_6": "Physics",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Nature",
    "sub_2": "Mathematics",
    "sub_3": "Mathematics",
    "sub_4": "Nature",
    "sub_5": "PE",
    "sub_6": "Art",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-04-06",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Biology",
    "sub_2": "History",
    "sub_3": "Biology",
    "sub_4": "English",
    "sub_5": "Music",
    "sub_6": "History",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "Chemistry",
    "sub_3": "Art",
    "sub_4": "Physics",
    "sub_5": "Geography",
    "sub_6": "Biology",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Art",
    "sub_2": "Art",
    "sub_3": "History",
    "sub_4": "English",
    "sub_5": "Physics",
    "sub_6": "Music",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "PE",
    "sub_3": "Chemistry",
    "sub_4": "Physics",
    "sub_5": "History",
    "sub_6": "Art",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Geography",
    "sub_2": "Art",
    "sub_3": "Nature",
    "sub_4": "Nature",
    "sub_5": "Biology",
    "sub_6": "History",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "PE",
    "sub_2": "PE",
    "sub_3": "Mathematics",
    "sub_4": "History",
    "sub_5": "Mathematics",
    "sub_6": "PE",
    "sub_7": "Literature",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Geography",
    "sub_2": "Music",
    "sub_3": "English",
    "sub_4": "Literature",
    "sub_5": "Chemistry",
    "sub_6": "Literature",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Literature",
    "sub_2": "Biology",
    "sub_3": "Music",
    "sub_4": "Nature",
    "sub_5": "Literature",
    "sub_6": "History",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "English",
    "sub_2": "Physics",
    "sub_3": "Chemistry",
    "sub_4": "Music",
    "sub_5": "Chemistry",
    "sub_6": "Music",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-07",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Art",
    "sub_2": "Geography",
    "sub_3": "Physics",
    "sub_4": "Mathematics",
    "sub_5": "Music",
    "sub_6": "Nature",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "Literature",
    "sub_3": "PE",
    "sub_4": "Literature",
    "sub_5": "Geography",
    "sub_6": "Mathematics",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "PE",
    "sub_2": "Literature",
    "sub_3": "Music",
    "sub_4": "Art",
    "sub_5": "History",
    "sub_6": "Literature",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "PE",
    "sub_2": "Geography",
    "sub_3": "Nature",
    "sub_4": "Nature",
    "sub_5": "Physics",
    "sub_6": "Literature",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "Music",
    "sub_3": "Biology",
    "sub_4": "Art",
    "sub_5": "English",
    "sub_6": "English",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "Literature",
    "sub_3": "Chemistry",
    "sub_4": "English",
    "sub_5": "Nature",
    "sub_6": "Nature",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Geography",
    "sub_2": "Literature",
    "sub_3": "Geography",
    "sub_4": "PE",
    "sub_5": "History",
    "sub_6": "Physics",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Geography",
    "sub_2": "Geography",
    "sub_3": "Music",
    "sub_4": "Nature",
    "sub_5": "Art",
    "sub_6": "History",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Biology",
    "sub_2": "Music",
    "sub_3": "History",
    "sub_4": "Music",
    "sub_5": "English",
    "sub_6": "Music",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-04-08",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "English",
    "sub_2": "PE",
    "sub_3": "Literature",
    "sub_4": "Art",
    "sub_5": "Nature",
    "sub_6": "Music",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "Literature",
    "sub_3": "Art",
    "sub_4": "Mathematics",
    "sub_5": "Literature",
    "sub_6": "Music",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "PE",
    "sub_3": "Chemistry",
    "sub_4": "Biology",
    "sub_5": "Geography",
    "sub_6": "Geography",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "PE",
    "sub_2": "English",
    "sub_3": "Literature",
    "sub_4": "English",
    "sub_5": "Physics",
    "sub_6": "Biology",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Literature",
    "sub_2": "Art",
    "sub_3": "Art",
    "sub_4": "Literature",
    "sub_5": "Nature",
    "sub_6": "Literature",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "English",
    "sub_2": "PE",
    "sub_3": "Chemistry",
    "sub_4": "Literature",
    "sub_5": "English",
    "sub_6": "Geography",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "English",
    "sub_3": "English",
    "sub_4": "Literature",
    "sub_5": "Art",
    "sub_6": "Art",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Art",
    "sub_2": "Literature",
    "sub_3": "Geography",
    "sub_4": "Literature",
    "sub_5": "PE",
    "sub_6": "PE",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "History",
    "sub_3": "History",
    "sub_4": "Biology",
    "sub_5": "English",
    "sub_6": "Literature",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-09",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "Biology",
    "sub_3": "Art",
    "sub_4": "Nature",
    "sub_5": "Physics",
    "sub_6": "Mathematics",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "Mathematics",
    "sub_3": "Physics",
    "sub_4": "Nature",
    "sub_5": "Physics",
    "sub_6": "Music",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "Biology",
    "sub_2": "Mathematics",
    "sub_3": "Mathematics",
    "sub_4": "PE",
    "sub_5": "Nature",
    "sub_6": "Literature",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "Geography",
    "sub_3": "Music",
    "sub_4": "Literature",
    "sub_5": "Literature",
    "sub_6": "Art",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "Literature",
    "sub_2": "Mathematics",
    "sub_3": "Chemistry",
    "sub_4": "Chemistry",
    "sub_5": "English",
    "sub_6": "Geography",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Music",
    "sub_2": "Art",
    "sub_3": "Music",
    "sub_4": "Physics",
    "sub_5": "Nature",
    "sub_6": "Physics",
    "sub_7": "PE",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "English",
    "sub_3": "Biology",
    "sub_4": "Chemistry",
    "sub_5": "Literature",
    "sub_6": "Art",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "Biology",
    "sub_2": "Mathematics",
    "sub_3": "Chemistry",
    "sub_4": "Physics",
    "sub_5": "Literature",
    "sub_6": "Geography",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Literature",
    "sub_2": "Physics",
    "sub_3": "Nature",
    "sub_4": "Literature",
    "sub_5": "Music",
    "sub_6": "Chemistry",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-12",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "Music",
    "sub_2": "Nature",
    "sub_3": "Chemistry",
    "sub_4": "History",
    "sub_5": "Physics",
    "sub_6": "Music",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Mathematics",
    "sub_2": "Nature",
    "sub_3": "Mathematics",
    "sub_4": "Nature",
    "sub_5": "Mathematics",
    "sub_6": "Mathematics",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "History",
    "sub_2": "Chemistry",
    "sub_3": "History",
    "sub_4": "Nature",
    "sub_5": "Geography",
    "sub_6": "Literature",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Mathematics",
    "sub_2": "Physics",
    "sub_3": "Music",
    "sub_4": "PE",
    "sub_5": "Biology",
    "sub_6": "Chemistry",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "History",
    "sub_2": "PE",
    "sub_3": "Chemistry",
    "sub_4": "Physics",
    "sub_5": "Physics",
    "sub_6": "Chemistry",
    "sub_7": "History",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "PE",
    "sub_3": "Chemistry",
    "sub_4": "English",
    "sub_5": "Physics",
    "sub_6": "Mathematics",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Mathematics",
    "sub_2": "Mathematics",
    "sub_3": "History",
    "sub_4": "Literature",
    "sub_5": "Mathematics",
    "sub_6": "Biology",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "PE",
    "sub_2": "Geography",
    "sub_3": "Literature",
    "sub_4": "Geography",
    "sub_5": "PE",
    "sub_6": "English",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "Geography",
    "sub_2": "Biology",
    "sub_3": "Chemistry",
    "sub_4": "Music",
    "sub_5": "Physics",
    "sub_6": "Physics",
    "sub_7": "Art",
    "sub_8": ""
  },
  {
    "date": "2026-04-13",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "PE",
    "sub_3": "Art",
    "sub_4": "Physics",
    "sub_5": "Biology",
    "sub_6": "Biology",
    "sub_7": "Biology",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "A",
    "yearClass": "1",
    "sub_1": "Geography",
    "sub_2": "Literature",
    "sub_3": "Music",
    "sub_4": "Literature",
    "sub_5": "Music",
    "sub_6": "Physics",
    "sub_7": "Music",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "B",
    "yearClass": "1",
    "sub_1": "English",
    "sub_2": "Nature",
    "sub_3": "Biology",
    "sub_4": "PE",
    "sub_5": "Music",
    "sub_6": "Art",
    "sub_7": "Geography",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "C",
    "yearClass": "1",
    "sub_1": "Physics",
    "sub_2": "Music",
    "sub_3": "Art",
    "sub_4": "Physics",
    "sub_5": "PE",
    "sub_6": "Geography",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "A",
    "yearClass": "2",
    "sub_1": "PE",
    "sub_2": "Art",
    "sub_3": "Art",
    "sub_4": "History",
    "sub_5": "Geography",
    "sub_6": "Chemistry",
    "sub_7": "Nature",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "B",
    "yearClass": "2",
    "sub_1": "Geography",
    "sub_2": "Chemistry",
    "sub_3": "Music",
    "sub_4": "Geography",
    "sub_5": "History",
    "sub_6": "Art",
    "sub_7": "English",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "C",
    "yearClass": "2",
    "sub_1": "Chemistry",
    "sub_2": "Geography",
    "sub_3": "Nature",
    "sub_4": "PE",
    "sub_5": "Nature",
    "sub_6": "Geography",
    "sub_7": "Chemistry",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "A",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "Mathematics",
    "sub_3": "Physics",
    "sub_4": "History",
    "sub_5": "English",
    "sub_6": "English",
    "sub_7": "Physics",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "B",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "Art",
    "sub_3": "Nature",
    "sub_4": "English",
    "sub_5": "Biology",
    "sub_6": "Biology",
    "sub_7": "Mathematics",
    "sub_8": ""
  },
  {
    "date": "2026-04-14",
    "letterClass": "C",
    "yearClass": "3",
    "sub_1": "History",
    "sub_2": "Mathematics",
    "sub_3": "English",
    "sub_4": "Art",
    "sub_5": "Literature",
    "sub_6": "English",
    "sub_7": "Nature",
    "sub_8": ""
  }
];
